spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microsigner
    username: user
    password: user
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  servlet:
    context-path: /microsigner-crypto
  error:
    include-message: always
  port: 8081