spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost:33066}/${MYSQL_DATABASE:microsigner_user}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  error:
    include-message: always
  port: ${APP_PORT:8080}
logging:
  level:
    org.springframework.boot: INFO